### PR TITLE
upgraded to latest @angular + ng-packagr

### PR DESCRIPTION
**Pull request by jabiinfante**
Upgraded to latest ng-packagr version.

I am not quite sure it was necessary in order to make it work on an angular 6.0.x project, but just wanted to make sure.

### CODE REVIEW

**Comment by mariohmol** [comment]
Hi, i'm trying to use this change but when i run npm test i receive

``` 
ERROR in src/app/app.component.spec.ts(2,36): error TS2307: Cannot find module 'ang-jsoneditor'.
src/app/demo/demo.component.ts(2,56): error TS2307: Cannot find module 'ang-jsoneditor'.

``` 

Any ideas?

**Comment by jabiinfante** [comment]
I have checked and tests were not passing before either...

It looks like some misconfig on the tsconfig.spec.ts:

```json
    "paths": {
      "@my/lib": [ "../dist/ang-jsoneditor" ]
    }
```

needs to be:
```json
"paths": {
      "ang-jsoneditor": [ "../ang-jsoneditor/src/public_api.ts" ]
    }
```

I have tried to fix the sample tests included and they are passing, allthought it's only testing the components are being created.

**Comment by mariohmol** [comment]
Awesome work!
